In [ ]:
import torch

In [ ]:
x = torch.rand(2,3) #0~1사이 랜덤 값
print(x)

tensor([[0.0389, 0.3324, 0.9968],
        [0.4638, 0.4997, 0.2810]])


In [ ]:
x = torch.randn(2,3) #샘플링 값 생성.
print(x)

tensor([[-0.2278, -2.1659, -0.0453],
        [ 0.1250, -0.3838,  0.3174]])


In [ ]:
x = torch.randint(2, 5, size = (2,3)) # 2 ~ 5사이 값 생성.
print(x)

tensor([[4, 4, 3],
        [4, 3, 2]])


In [ ]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
ref = torch.rand(4,5)
x = torch.zeros_like(ref) #이렇게 껴넣기도 가능
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x = torch.ones(2,3) # 1값으로 채워넣기 가능.
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
ref = torch.rand(4,5)
x = torch.ones_like(ref)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
x = torch.rand(2,3)
print(x.type())
print(type(x))

torch.FloatTensor
<class 'torch.Tensor'>


In [ ]:
double_x = x.type(dtype = torch.DoubleTensor) # DoubleTensor형태로.
print(double_x.type())

torch.DoubleTensor


In [ ]:
int_x = x.type_as(torch.IntTensor())
print(int_x.type())

torch.IntTensor


In [ ]:
import numpy as np

x1 = np.ndarray(shape = (2,3), dtype = int, buffer = np.array([1,2,3,4,5,6]))
print(x1)

x2 = torch.from_numpy(x1) # numpy 배열을 torch텐서 변환 가능.

print(x2)
print(x2.type())

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


In [ ]:
x3 = x2.numpy()
print(x3)

[[1 2 3]
 [4 5 6]]


In [ ]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
cpu = torch.device('cpu')
gpu = torch.device('cuda')

if torch.cuda.is_available():
    
    x_gpu = x.to(gpu)
    print(x_gpu)

x_cpu = x_gpu.to(cpu) #GPU로 바꾸고 해야 가능.
print(x_cpu)

NameError: ignored

In [ ]:
x = torch.FloatTensor(10, 12, 3, 3)
print(x.size())
print(x.size()[1:2])

torch.Size([10, 12, 3, 3])
torch.Size([12])


In [ ]:
x = torch.FloatTensor([10, 12, 3, 3])
print(x.size())
print(x.size()[0]) # 1값으로 받아와서 4.

torch.Size([4])
4


In [ ]:
x = torch.randn(4,3)
print(x)

tensor([[-0.0174, -0.6219, -1.4803],
        [ 1.5816, -1.2787, -1.2728],
        [-0.5718, -0.4154, -1.1340],
        [-0.1074,  1.4945,  1.6843]])


In [ ]:
print(x[1:3, :]) # 1번, 2번 인덱스 전체

tensor([[ 1.5816, -1.2787, -1.2728],
        [-0.5718, -0.4154, -1.1340]])


In [ ]:
print(x)

print('\n')

selected = torch.index_select(x, dim = 1, index = torch.LongTensor([0,2])) #1,3번째 열. 출력
print(selected)

tensor([[-0.0174, -0.6219, -1.4803],
        [ 1.5816, -1.2787, -1.2728],
        [-0.5718, -0.4154, -1.1340],
        [-0.1074,  1.4945,  1.6843]])


tensor([[-0.0174, -1.4803],
        [ 1.5816, -1.2728],
        [-0.5718, -1.1340],
        [-0.1074,  1.6843]])


In [ ]:
x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1], [0,1,0]])
out = torch.masked_select(x, mask) # 1값에 자동으로 지정. mask 씌우기 생각.

print(x)
print(mask)
print(out)

tensor([[-0.4139, -2.4438,  0.1346],
        [-1.3912,  0.6148,  0.5530]])
tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)
tensor([0.1346, 0.6148])


<ipython-input-22-e6f357f2f8b2>:3: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1729.)
  out = torch.masked_select(x, mask) # 1값에 자동으로 지정. mask 씌우기 생각.


In [ ]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])

z1 = torch.cat([x,y], dim = 0) # 행 기준 합치기
z2 = torch.cat([x,y], dim = 1) # 열 기준 합치기

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


In [ ]:
x = torch.FloatTensor([[1,2,3], [4,5,6]]) #2 ,3배열
x_stack = torch.stack([x, x, x, x], dim = 0) #차원 생성 4,2,3배열

print(x_stack)
print(x_stack.size())

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])
torch.Size([4, 2, 3])


In [ ]:
x_1, x_2 = torch.chunk(z1, 2, dim = 0) #2개로 분열 # 행 기준 분열
y_1, y_2, y_3 = torch.chunk(z1, 3, dim = 1) #3개로 분열 # 열 기준 분열

print(z1)
print('\n')
print(x_1)
print(x_2)

print('\n')
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])


tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [ ]:
#분해.

x1, x2 = torch.split(z1, 2, dim = 0)
y1 = torch.split(z1, 2, dim = 1) 

print(z1, x1, x2, sep = '\n')

print("this is y1:")
for i in y1:
    print(i)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
this is y1:
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [ ]:
# 차원 압축. squeeze()

x1 = torch.FloatTensor(10, 1, 3, 1, 4)
x2 = torch.squeeze(x1) #압축.

print(x1.size(), x2.size(), sep = '\n')

torch.Size([10, 1, 3, 1, 4])
torch.Size([10, 3, 4])


In [ ]:
import torch

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim = 0) #차원 하나 늘리기. 앞에 1 추가 된거 확인.
#x3 = torch.unsqueeze(x1, dim = 1)

print(x1.size())
print(x2.size())
#print(x3.size())

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


In [ ]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4), a = 0, b = 9) #0~9사이값으로 3,4배열 생성

x2 = init.normal_(torch.FloatTensor(3,4), std = 0.2) # 값 0.2로 3,4 배열 생성.

x3 = init.constant_(torch.FloatTensor(3,4), 3.1415) #3.1415 3,4배열 생성.

print(x1,x2,x3, sep = '\n\n')


tensor([[3.3703, 4.2554, 0.9378, 8.1855],
        [8.5520, 5.9004, 3.0061, 2.8841],
        [0.6861, 4.1525, 0.6266, 8.4618]])

tensor([[-0.1080, -0.2389, -0.0444,  0.0381],
        [-0.0397, -0.4064,  0.3551, -0.0239],
        [-0.4740, -0.0746,  0.0825, -0.0185]])

tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])

add = torch.add(x1, x2)

print(x1)
print(x2)

print(add)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1, 10)

print(x1)
print(x2)
print(x1 + 10)
print(x2 - 10)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])

x3 = torch.mul(x1, x2)
print(x3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1 * 10

print(x2)

tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])

x3 = torch.div(x1, x2)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
print(x1 / 5)

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])


In [ ]:
x1 = torch.FloatTensor(3,4)
torch.pow(x1, 2)
print(x1 ** 2)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [73.1369, 34.8142,  9.0364,  8.3182],
        [ 0.4707, 17.2429,  0.3926, 71.6028]])


In [ ]:
x1 = torch.FloatTensor(3,4)
torch.exp(x1) #exponential 연산. 쓰레기 값. 알아서 배열 맞춰서 채워줌

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0860, 1.0187]])

In [ ]:
x1 = torch.FloatTensor(3,4)
torch.log(x1)

tensor([[-76.6464,     -inf,     -inf,     -inf],
        [  4.2923,   3.5500,   2.2013,   2.1184],
        [ -0.7536,   2.8474,  -0.9350,   4.2711]])

In [ ]:
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1, x2) #행렬곱 계산

tensor([[-1.3026e-39, -5.9417e+27,  5.7269e-34,  0.0000e+00,  4.5603e-35],
        [-2.3346e-06, -5.9417e+27,  9.6228e-34,  2.9108e-34,  4.5603e-35],
        [-2.3346e-06, -6.0527e+27,  1.0115e-33,  2.9108e-34,  4.9526e-35]])

In [ ]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)

torch.bmm(x1, x2).size()

torch.Size([10, 3, 5])

In [ ]:
x1 = torch.tensor([2,3])
x2 = torch.tensor([2,1])
# (2 x 2) + (3 x 1)
torch.dot(x1,x2)

tensor(7)

In [ ]:
x1 = torch.tensor([[1,2], [3,4]])
print(x1)
print(x1.t()) # 행과 열이 바뀜. .t()

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [ ]:
x1 = torch.FloatTensor(10,3,4)
print(x1.size())

print('\n')

print(torch.transpose(x1, 1, 2).size()) #2번째, 3번째 위치 바뀌기.
print(x1.transpose(1,2).size()) #위와 동일 코드

torch.Size([10, 3, 4])


torch.Size([10, 4, 3])
torch.Size([10, 4, 3])


In [ ]:
x = torch.tensor([1., 2., 3.], requires_grad = True) #기울기 계산 키고 해줘야. 가능. 'requires_grad = True'이거.
y = torch.tensor([4., 5., 6.], requires_grad = True)

print(x, x.requires_grad)
z = x + y

z.sum().backward()

tensor([1., 2., 3.], requires_grad=True) True


In [ ]:
print(x.requires_grad, y.requires_grad) #기울기 계산 켜줘서 True

with torch.no_grad():
    z = x + y
    print(z.requires_grad) #기울기 있는데, 없냐로 물어봐서 False

True True
False


In [ ]:
cpu = torch.device('cpu')
gpu = torch.device('cuda')

x = torch.tensor([1,2,3], dtype = torch.float64, device = cpu, requires_grad = True)
print(x.device)

if torch.cuda.is_available():
    x = x.to(gpu)
    print(x.device)

cpu


음... 텐서플로랑 달라서 매우 헷갈린다.