In [2]:
##모양 & 자료형

import cv2
import numpy as np

img = cv2.imread('Lenna.png') #이미지 불러오기

print('img.ndim = ', img.ndim) # 3차원 배열
print('img.shape = ', img.shape) # 512 x 512크기의 3채널 영상
print('img.dtype = ', img.dtype) # 원래의 type은 uint8형태

img = img.astype(np.int32) # 타입 변환 후 
print('img.dtype = ', img.dtype) #결과는 int32형태

img = np.uint8(img) #타입 변환 후
print('img.dtype = ', img.dtype) # 결과는 uint8 형태

img.ndim =  3
img.shape =  (512, 512, 3)
img.dtype =  uint8
img.dtype =  int32
img.dtype =  uint8


In [3]:
##모양 변경

img = cv2.imread('Lenna.png', cv2.IMREAD_GRAYSCALE) #이미지를 grayscale로 읽어오고.
print('img.shape = ', img.shape) #모양새는 512,512 크기

img = img.flatten() # flatten써서 1차원 배열로 변경
print('img.shape = ', img.shape)

img = img.reshape(-1,512,512) #다시 reshape써서 1,512,512크기로(원본 데이터는 변경  X)
print('img.shape = ', img.shape)

cv2.imshow('img', img[0]) 
cv2.waitKey()
cv2.destroyAllWindows()

img.shape =  (512, 512)
img.shape =  (262144,)
img.shape =  (1, 512, 512)


In [4]:
#화소. 그레이스케일 영상

img = cv2.imread('Lenna.png', cv2.IMREAD_GRAYSCALE)

img[100,200] = 0 # Y = 100, X = 200을 0으로
print(img[100:110, 200:210]) # y축 100~109, x축 200~209 화소값 출력

img[100:400, 200:300] = 0 # y축 100~399, x축 200~299까지 0으로 지정

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[  0 153 150 141 151 150 151 145 144 144]
 [146 144 151 155 148 149 146 148 145 145]
 [139 146 157 148 142 146 148 146 144 140]
 [145 153 146 135 139 147 149 148 140 138]
 [151 149 139 142 148 150 149 141 142 147]
 [151 144 143 151 152 150 139 138 145 144]
 [149 151 149 151 149 148 150 143 142 141]
 [159 149 145 146 150 151 152 144 132 137]
 [151 144 144 144 152 149 139 134 140 144]
 [142 142 151 151 143 142 133 143 146 136]]


In [5]:
img = cv2.imread('Lenna.png')

img[100,200] = [255,0,0] # BGR컬러 파랑이로 변경
print(img[100, 200:210]) # y = 100, x = 200~209로 지정 출력.

img[100:400, 200:300] = [255,0,0] # y축 100~399, x축 200~299까지. 파랑이로 변경

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[255   0   0]
 [109 117 213]
 [113 115 208]
 [114 101 199]
 [121 116 207]
 [105 114 209]
 [112 113 212]
 [107 109 204]
 [117 108 200]
 [110 109 202]]


In [6]:
img = cv2.imread('Lenna.png')

img[100:400, 200:300, 0] = 255 # B채널 255
img[100:400, 300:400, 1] = 255 # G 채널 255
img[100:400, 400:500, 2] = 255 # R 채널 255

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()